services:
  - postgresql
before_script:
  - psql -c 'create database talon_test;' -U postgres
  - nohup phantomjs --wd &
language: elixir
elixir:
  - 1.4
otp_release:
  - 19.3
  - 18.3
sudo: false
script: mix test
notification:
  recipients:
    - smpallen99@yahoo.com
